#!/bin/sh
QUALITY=100

# Get a screenshot and get the filename of it
SCREENSHOT=$(scrot -q $QUALITY -se 'echo $f')

# Create a directory from the first argument and move the screenshot into it.
mkdir -p $1
mv $SCREENSHOT $1/

# Upload the screenshot with cloudapp
URL=$(cloudapp upload $1/$SCREENSHOT)

# Send a notification to indicate completion
notify-send -a cloudapp CloudApp $URL
